### ISSUE TITLE
Swagger query parameters of type "boolean" are not parsed correctly

### ISSUE THREAD

**Issue by stoberov** [softwaregroup-bg/ut-port-swagger#22]
Sometimes, you may want to add a **boolean** query parameter for GET requests. In swagger.json, that would be:

```js
"parameters": [
    {
        "name": "detailed",
        "in": "query",
        "description": "Optionally include additional details",
        "type": "boolean"
    }
]
```

When the requests hits the back-end, the parameter is received as a string:
```js
{
    "detailed": "true" // or "false"
}
```
 
It would be nice if the parameters are parsed automatically to JavaScript booleans - **true** or **false**

**Comment by stambata** [comment]
Should be fixed in version 3.1.0-auditAndReport.4 and respectively for 3.1.0 and up.

Reference commit: https://github.com/softwaregroup-bg/ut-port-swagger/commit/45615769e51890caedb9509c38e8b63e833b7c81
